# MIT License
#
# Copyright (c) 2021-2025 Reik Steinert, Mikael Andersson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

system_automations:
  automation:
    - id: ha_start
      alias: HA Start
      trigger:
        platform: homeassistant
        event: start
      action:
        service: script.turn_on
        entity_id: script.ha_start

    - id: scheduled_restart_host_on_lost_inverter
      alias: Scheduled Restart Host On Lost Inverter
      trigger:
        platform: time
        at: "02:00:00"
      # Only reboot host if no connection to inverter
      condition: "{{ states('sensor.solax1_inverter_state') == 'unknown' }}"
      action:
        - service: hassio.host_reboot

      # Since Studio Code Server is hogging the CPU sometimes,
      # ensure to stop it in case we forget it to stop it manually.
    - id: studio_code_server_stop_on_hogged_cpu
      alias: Studio Code Server - Stop On Hogged CPU
      description: ""
      triggers:
        - trigger: numeric_state
          entity_id: sensor.processor_use
          for:
            hours: 0
            minutes: 15
            seconds: 0
          above: 40
        - trigger: time
          at: "05:00:00"
      conditions: []
      actions:
        - action: hassio.addon_stop
          metadata: {}
          data:
            addon: a0d7b954_vscode
      mode: single
