services:
  home-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-assistant-dev
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Stockholm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/api/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MariaDB for development (if needed)
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: homeassistant
      MYSQL_DATABASE: homeassistant
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: homeassistant
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    profiles:
      - database

  # Optional: MQTT broker for development
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto-dev
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    profiles:
      - mqtt

volumes:
  mariadb_data: