# MIT License
#
# Copyright (c) 2021-2022 Reik Steinert
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

prices_use:
  binary_sensor:
    - platform: template
      sensors:
        use_on_next_occasion:
          friendly_name: "Use On Next Occasion"
          icon_template: mdi:cash-minus
          value_template: >
            {{ states('sensor.electricity_price_buy') | float(0) >= states('sensor.electricity_price_limit_use') | float(0) }}

        #-----------------------------------------------------------------------------------------------------------------------------------
  sensor:
    - platform: template
      sensors:
        electricity_price_limit_use:
          friendly_name: "Electricity Price Limit Use"
          icon_template: mdi:cash
          unit_of_measurement: "SEK/kWh"
          value_template: >
            {% set electricity_price_limit_sell = states('sensor.electricity_price_limit_sell') | float(0) %}
            {% set electricity_price_bottom = states('sensor.electricity_price_bottom') | float(0) %}
            {% set kwh_price_battery = states('input_number.kwh_price_battery') | float(0) %}
            {% set limit_value = electricity_price_bottom + kwh_price_battery %}

            {% if electricity_price_limit_sell <= limit_value %}
                {# Om electricity_price_limit_sell är mindre än eller lika med limit_value, sätt det till limit_value #}
                {% set new_value = limit_value %}
                {{ new_value | round(3) }}
            {% else %}
                {{ electricity_price_limit_sell | round(3) }}
            {% endif %}

        #-----------------------------------------------------------------------------------------------------------------------------------
