# .devcontainer/docker-compose.yml
version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    network_mode: host
    environment:
      - DOCKER_HOST=unix:///var/run/docker-host.sock

---

# .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/python:3.11

# Install Docker CLI for container management
RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*

# Install Python development dependencies
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

# Install Home Assistant for development
RUN pip install homeassistant

# Create workspace
WORKDIR /workspace

# Set up git safe directory
RUN git config --global --add safe.directory /workspace