# MIT License
#
# Copyright (c) 2021-2022 Reik Steinert
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

power_inputs:
  input_boolean:
    force_power:
      name: Force Power
      icon: mdi:transmission-tower

    fix_price_mode:
      name: Fix Price Mode
      icon: mdi:cash-lock

    charge_battery_override:
      name: Charge Battery Override
      icon: mdi:battery-arrow-up

    use_battery_override:
      name: Use Battery Override
      icon: mdi:battery-arrow-down

  #***************************************************************************************************

  input_number:
    hours_to_charge:
      name: Hours To Charge
      min: 1
      max: 16
      step: 1
      unit_of_measurement: "h"
      icon: mdi:clock
      mode: box

    average_charge_power:
      name: Average Charge Power
      min: 1.0
      max: 12.0
      step: 0.1
      unit_of_measurement: "kW"
      icon: mdi:sine-wave
      mode: box

    hours_to_sell:
      name: Hours To Sell
      min: 1
      max: 12
      step: 1
      unit_of_measurement: "h"
      icon: mdi:clock
      mode: box

    soc_min:
      name: SOC Min
      min: 10
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-charging-low
      mode: box

    soc_backup:
      name: SOC Backup
      min: 10
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-charging-low
      mode: box

    previous_soc_backup:
      name: "Previous SOC Backup"
      min: 0
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-charging-low
      mode: box

    soc_max:
      name: SOC Max
      min: 10
      max: 100
      step: 1
      unit_of_measurement: "%"
      icon: mdi:battery-charging-high
      mode: box
